server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.101.14/yhlm_test?useSSL=false
      username: yhlm
      password: yhlm



#打开Mybatis-plus的日志
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mp.domain.Book


reggie:
  path: E://output//picStore//